version: "3.9"
services:
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
    depends_on:
      - db
      - webdriver_chrome
  webdriver_chrome:
    image: selenium/standalone-chrome
volumes:
  db-volume:
    driver: local
