name: Test
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    container:
      image: circleci/ruby:2.6.3-buster-node-browsers
    steps:
      - uses: actions/checkout@v1
      - name: setup bundle
        run: bundle install
      - name: setup yarn
        run: |
          npm install -g yarn
          yarn install
      - name: setup migrate
        run: rails db:setup RAILS_ENV=test
      - name: copy file
        run: cp spec/support/capybara-ci.rb.example spec/support/capybara.rb
      - name: run spec
        run: bundle exec rspec
