name: Test
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    container:
      image: circleci/ruby:2.6.7-node-browsers
    steps:
      - uses: actions/checkout@v1
      - name: set permission to circle ci
        run: sudo chown -R circleci .
      - name: setup bundle
        run: bundle install
      - name: setup yarn
        run: yarn install
      - name: setup migrate
        run: rails db:create db:migrate RAILS_ENV=test
      - name: copy file
        run: sudo cp spec/support/capybara-ci.rb.example spec/support/capybara.rb
      - name: run spec
        run: bundle exec rspec
      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: 'RSpec'
          url: ${{ secrets.SLACK_WEBHOOK }}
          icon_emoji: ":robot_face:"
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
  rubocop:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.7
    steps:
      - uses: actions/checkout@v1
      - name: setup bundle
        run: bundle install
      - name: run rubocop
        run: bundle exec rubocop
      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: 'Rubocop'
          url: ${{ secrets.SLACK_WEBHOOK }}
          icon_emoji: ":robot_face:"
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
