name: Add Label
on:
  pull_request:

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Set issue number
        run: |
          issue_number=${${{github.ref}} | grep -o "[0-9]\."}
          echo issue_number
          echo "ISSUE_NUMBER=${issue_number}" >> $GITHUB_ENV
      - name: Add label
        uses: actions/github-script@v6
        env:
          ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
        with:
          script: |
            const { ISSUE_NUMBER } = process.env
            github.rest.issues.addLabels({
              issue_number: ,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['task']
            })
