on:
  pull_request:
    types: [opened, edited]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Set issue number
        run: |
          issue_number=${${{github.ref}} | grep -o "[0-9]\."}
          echo issue_number
      - name: Add label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['task']
            })
